### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by rahooftkh** [icreated/webstore-api#2]
hi i am using idempiere version 7.1 
using the webstore-api try to run mvn install got some errors
 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
Downloading from jr-ce-releases: https://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases/org/idempiere/org.idempiere.p2.targetplatform/7.1.0-SNAPSHOT/org.idempiere.p2.targetplatform-7.1.0-SNAPSHOT.target
Downloading from jenkins: https://repo.jenkins-ci.org/releases/org/idempiere/org.idempiere.p2.targetplatform/7.1.0-SNAPSHOT/org.idempiere.p2.targetplatform-7.1.0-SNAPSHOT.target
[ERROR] Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact org.idempiere:org.idempiere.p2.targetplatform:target:7.1.0-SNAPSHOT -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact org.idempiere:org.idempiere.p2.targetplatform:target:7.1.0-SNAPSHOT
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:120)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.RuntimeException: Could not resolve target platform specification artifact org.idempiere:org.idempiere.p2.targetplatform:target:7.1.0-SNAPSHOT
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.addTargetArtifact (DefaultTargetPlatformConfigurationReader.java:389)
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.setTarget (DefaultTargetPlatformConfigurationReader.java:342)
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.getTargetPlatformConfiguration (DefaultTargetPlatformConfigurationReader.java:75)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject (DefaultTychoResolver.java:87)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:90)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by icreated** [comment]
Hi Rahoof,

I've done some modifications for migration to 7.1.0 version & I put it to
github. Could you check if it works? Here is my logs:

(base) spok@ubuspok:/applis/repository/git/icreated/org.icreated.webstore.api$
mvn verify
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by
com.google.inject.internal.cglib.core.$ReflectUtils$1
(file:/usr/share/maven/lib/guice.jar) to method
java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of
com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal
reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject:
org.idempiere:org.icreated.wstore.api:7.1.0-SNAPSHOT @
/applis/repository/git/icreated/org.icreated.webstore.api/pom.xml
[INFO] Fetching p2.index from
https://download.eclipse.org/eclipse/updates/4.10/
[INFO] Fetching p2.index from
https://download.eclipse.org/eclipse/updates/4.10/
[INFO] Adding repository https://download.eclipse.org/eclipse/updates/4.10
[INFO] Fetching p2.index from
https://download.eclipse.org/eclipse/updates/4.10/R-4.10-201812060815/
[INFO] Fetching p2.index from
https://download.eclipse.org/eclipse/updates/4.10/R-4.10-201812060815/
[INFO] Fetching p2.index from
https://download.eclipse.org/tools/orbit/downloads/drops/R20181128170323/repository/
[INFO] Fetching p2.index from
https://download.eclipse.org/tools/orbit/downloads/drops/R20181128170323/repository/
[INFO] Adding repository
https://download.eclipse.org/tools/orbit/downloads/drops/R20181128170323/repository
[INFO] Fetching p2.index from
https://download.eclipse.org/tools/orbit/downloads/drops2/R20181128170323/repository/
[INFO] Fetching p2.index from
https://download.eclipse.org/tools/orbit/downloads/drops2/R20181128170323/repository/
[INFO] Adding repository
https://raw.githubusercontent.com/idempiere/binary.file/master/p2.maven/maven-p2-R20191224
[INFO] Fetching content.jar from
https://raw.githubusercontent.com/idempiere/binary.file/master/p2.maven/maven-p2-R20191224/
(110,08kB)
[INFO] Fetching content.jar from
https://raw.githubusercontent.com/idempiere/binary.file/master/p2.maven/maven-p2-R20191224/
(110,08kB)
[INFO] Adding repository
https://raw.githubusercontent.com/idempiere/binary.file/master/p2.maven/org.idempiere.webservice.client-p2-R20190412
[INFO] Fetching content.jar from
https://raw.githubusercontent.com/idempiere/binary.file/master/p2.maven/org.idempiere.webservice.client-p2-R20190412/
(13,48kB)
[INFO] Fetching content.jar from
https://raw.githubusercontent.com/idempiere/binary.file/master/p2.maven/org.idempiere.webservice.client-p2-R20190412/
(13,48kB)
[INFO] Resolving dependencies of MavenProject:
org.idempiere:org.icreated.wstore.api:7.1.0-SNAPSHOT @
/applis/repository/git/icreated/org.icreated.webstore.api/pom.xml
[WARNING] The following locally built units have been used to resolve
project dependencies:
[WARNING]   org.apache.ecs/7.1.0.202004141005
[WARNING]   org.adempiere.base/7.1.0.202004141004
[INFO] Resolving class path of MavenProject:
org.idempiere:org.icreated.wstore.api:7.1.0-SNAPSHOT @
/applis/repository/git/icreated/org.icreated.webstore.api/pom.xml
[INFO]
[INFO] ---------------< org.idempiere:org.icreated.wstore.api
>----------------
[INFO] Building org.icreated.wstore.api 7.1.0-SNAPSHOT
[INFO] ---------------------------[ eclipse-plugin
]---------------------------
[INFO]
[INFO] --- tycho-packaging-plugin:1.5.0:build-qualifier
(default-build-qualifier) @ org.icreated.wstore.api ---
[INFO] The project's OSGi version is 7.1.0.202007212045
[INFO]
[INFO] --- tycho-packaging-plugin:1.5.0:validate-id (default-validate-id) @
org.icreated.wstore.api ---
[INFO]
[INFO] --- tycho-packaging-plugin:1.5.0:validate-version
(default-validate-version) @ org.icreated.wstore.api ---
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (auto-clean) @
org.icreated.wstore.api ---
[INFO] Deleting
/applis/repository/git/icreated/org.icreated.webstore.api/target
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @
org.icreated.wstore.api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory
/applis/repository/git/icreated/org.icreated.webstore.api/src/main/resources
[INFO]
[INFO] --- tycho-compiler-plugin:1.5.0:compile (default-compile) @
org.icreated.wstore.api ---
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:testResources
(default-testResources) @ org.icreated.wstore.api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory
/applis/repository/git/icreated/org.icreated.webstore.api/src/test/resources
[INFO]
[INFO] --- tycho-source-plugin:1.5.0:plugin-source (plugin-source) @
org.icreated.wstore.api ---
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:copy (copy_libs) @
org.icreated.wstore.api ---
[INFO] Configured Artifact: io.jsonwebtoken:jjwt-api:0.10.5:jar
[INFO] Configured Artifact: io.jsonwebtoken:jjwt-impl:0.10.5:jar
[INFO] Configured Artifact: io.jsonwebtoken:jjwt-jackson:0.10.5:jar
[INFO] Configured Artifact: io.swagger.core.v3:swagger-jaxrs2:2.0.8:jar
[INFO] Configured Artifact: io.swagger.core.v3:swagger-core:2.0.8:jar
[INFO] Configured Artifact:
io.swagger.core.v3:swagger-jaxrs2-servlet-initializer:2.0.8:jar
[INFO] Configured Artifact: io.swagger.core.v3:swagger-annotations:2.0.8:jar
[INFO] Configured Artifact: io.swagger.core.v3:swagger-models:2.0.8:jar
[INFO] Configured Artifact: io.swagger.core.v3:swagger-integration:2.0.8:jar
[INFO] Configured Artifact:
com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.9:jar
[INFO] Configured Artifact: org.yaml:snakeyaml:1.24:jar
[INFO] Configured Artifact: io.github.classgraph:classgraph:4.8.43:jar
[INFO] Copying jjwt-api-0.10.5.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/jjwt-api.jar
[INFO] Copying jjwt-impl-0.10.5.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/jjwt-impl.jar
[INFO] Copying jjwt-jackson-0.10.5.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/jjwt-jackson.jar
[INFO] Copying swagger-jaxrs2-2.0.8.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/swagger-jaxrs2.jar
[INFO] Copying swagger-core-2.0.8.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/swagger-core.jar
[INFO] Copying swagger-jaxrs2-servlet-initializer-2.0.8.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/swagger-jaxrs2-servlet-initializer.jar
[INFO] Copying swagger-annotations-2.0.8.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/swagger-annotations.jar
[INFO] Copying swagger-models-2.0.8.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/swagger-models.jar
[INFO] Copying swagger-integration-2.0.8.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/swagger-integration.jar
[INFO] Copying jackson-dataformat-yaml-2.9.9.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/jackson-dataformat-yaml.jar
[INFO] Copying snakeyaml-1.24.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/snakeyaml.jar
[INFO] Copying classgraph-4.8.43.jar to
/applis/repository/git/icreated/org.icreated.webstore.api/WEB-INF/lib/classgraph.jar
[INFO]
[INFO] --- target-platform-configuration:1.5.0:target-platform
(default-target-platform) @ org.icreated.wstore.api ---
[INFO]
[INFO] --- tycho-packaging-plugin:1.5.0:package-plugin
(default-package-plugin) @ org.icreated.wstore.api ---
[INFO] Building jar:
/applis/repository/git/icreated/org.icreated.webstore.api/target/org.icreated.wstore.api-7.1.0-SNAPSHOT.jar
[INFO]
[INFO] --- tycho-p2-plugin:1.5.0:p2-metadata-default
(default-p2-metadata-default) @ org.icreated.wstore.api ---
[INFO]
------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO]
------------------------------------------------------------------------
[INFO] Total time:  12.464 s
[INFO] Finished at: 2020-07-21T22:46:06+02:00
[INFO]
------------------------------------------------------------------------
(base) spok@ubuspok
:/applis/repository/git/icreated/org.icreated.webstore.api$

**Comment by rahooftkh** [comment]
ok thanks

**Comment by rahooftkh** [comment]
hi sir 
i am new with java
how can i integrate this with idempiere
 
added webstore code to idempiere workspace  ,add jar to osgi package 
but when start package got an error
org.osgi.framework.BundleException: Could not resolve module: org.icreated.wstore.api [336]
  Unresolved requirement: Import-Package: org.glassfish.jersey.client; version="2.22.1"

	at org.eclipse.osgi.container.Module.start(Module.java:451)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:431)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:450)
	at org.apache.felix.webconsole.internal.core.InstallHelper.doRun(InstallHelper.java:67)
	at org.apache.felix.webconsole.internal.core.BaseUpdateInstallHelper.doRun(BaseUpdateInstallHelper.java:99)
	at org.apache.felix.webconsole.internal.core.BaseUpdateInstallHelper.run(BaseUpdateInstallHelper.java:171)
	at java.base/java.lang.Thread.run(Thread.java:834)
